-- MySQL Script generated by MySQL Workbench
-- Sun Feb 26 20:55:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chloe_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chloe_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chloe_database` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `chloe_database` ;

-- -----------------------------------------------------
-- Table `chloe_database`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloe_database`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `email_usuario` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `nivel` VARCHAR(25) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `last_login` DATETIME NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chloe_database`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloe_database`.`reserva` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `qtd_pessoas` INT UNSIGNED NOT NULL,
  `check_in` DATETIME NOT NULL,
  `check_out` DATETIME NOT NULL,
  `cupom` VARCHAR(45) NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `total_desconto` DECIMAL(10,2) NOT NULL,
  `confirmacao` TINYINT(1) NOT NULL DEFAULT 0,
  `data_confirmacao` DATETIME NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_reserva_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `chloe_database`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chloe_database`.`acomodacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloe_database`.`acomodacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `imagem` VARCHAR(255) NOT NULL,
  `reserva_id` INT NOT NULL,
  `reserva_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `reserva_id`, `reserva_usuario_id`),
  INDEX `fk_acomodacoes_reserva1_idx` (`reserva_id` ASC, `reserva_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_acomodacoes_reserva1`
    FOREIGN KEY (`reserva_id` , `reserva_usuario_id`)
    REFERENCES `chloe_database`.`reserva` (`id` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chloe_database`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloe_database`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chloe_database`.`avaliacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloe_database`.`avaliacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pontuacao` INT UNSIGNED NOT NULL DEFAULT 0,
  `descricao` LONGTEXT NULL,
  `status` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_avaliacoes_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacoes_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `chloe_database`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chloe_database`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloe_database`.`servicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_servico` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(255) NOT NULL,
  `reserva_id` INT NOT NULL,
  `reserva_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `reserva_id`, `reserva_usuario_id`),
  INDEX `fk_servicos_reserva1_idx` (`reserva_id` ASC, `reserva_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_servicos_reserva1`
    FOREIGN KEY (`reserva_id` , `reserva_usuario_id`)
    REFERENCES `chloe_database`.`reserva` (`id` , `usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `chloe_database`.`consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chloe_database`.`consumo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_item` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `qtd_item` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_consumo_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_consumo_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `chloe_database`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
